CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  bio VARCAHR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255)
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  uploader_id INTEGER NOT NULL,
  username VARCHAR(50) NOT NULL,
  caption VARCHAR(1000) NOT NULL,
  img_url VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (uploader_id) REFERENCES users(id)
);

CREATE TABLE likes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  posts_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (posts_id) REFERENCES posts(id)
);

